export const campsites = [
  {
    id: "deception-pass",
    name: "Deception Pass State Park",
    region: "San Juan Islands & Puget Sound",
    location: "Anacortes, WA",
    lat: 48.3954,
    lng: -122.6553,
    platform: "WA State Parks",
    bookingUrl: "https://washington.goingtocamp.com",
    image: "https://photos.thedyrt.com/photo/639993/media/washington-deception-pass-state-park_5cc77c5a-4504-4b32-af89-88b42378c8f2.jpg",
    pricePerNight: 35,
    reservationFee: 8,
    rating: 4.5,
    reviews: 109,
    sites: 326,
    siteTypes: ["tent", "RV", "cabin"],
    showers: { type: "coin-op", cost: "$1 = 4 tokens (3 min each)", hours: "all day", seasonal: "Spring–Thanksgiving" },
    amenities: ["hot showers", "flush toilets", "fire pit", "picnic table", "potable water", "boat launch"],
    highlights: "WA's most popular state park. Dramatic bridge 180ft above tidal currents, old growth trails, beach access.",
    driveFromSeattle: "1.5 hr",
    season: "Year-round (water spring–Thanksgiving)",
    alerts: ["Bowman Bay pier closed indefinitely", "No vehicles over 25ft at West Beach"],
    tips: "Cranberry Loop has the best shade. Sites C-30 to C-50 are closest to showers.",
    availability: generateAvailability(0.6),
    socialReviews: [
      { source: "Reddit r/WACamping", user: "u/PNW_hiker92", text: "Cranberry Loop is the move. We got site C-38 and the walk to showers was maybe 2 minutes. The bridge views at sunset are unreal.", date: "2025-08" },
      { source: "The Dyrt", user: "CampingMom_WA", text: "Came with three kids and they loved the tidepools at Rosario Beach. Showers were clean but bring tokens — the machine at the booth only takes $1 bills.", date: "2025-07" },
      { source: "Reddit r/CampingGear", user: "u/tentlife_best", text: "Heads up — Quarry Pond sites are MUCH quieter than Cranberry if you want to actually sleep. Cranberry gets rowdy on summer weekends.", date: "2025-09" },
    ]
  },
  {
    id: "shangri-la-push",
    name: "Shangri La Push",
    region: "Olympic Peninsula",
    location: "Forks, WA",
    lat: 47.9071,
    lng: -124.5887,
    platform: "Hipcamp",
    bookingUrl: "https://www.hipcamp.com/en-US/washington/forks",
    image: "https://hipcamp-res.cloudinary.com/f_jpg,c_fill,w_800,h_600,q_80/v1622419894/campground-photos/xfsp78b76jixzgmitbnw.jpg",
    pricePerNight: 45,
    reservationFee: 0,
    rating: 4.9,
    reviews: 2124,
    sites: 15,
    siteTypes: ["tent", "RV"],
    showers: { type: "free", cost: "Free hot water", hours: "all day", seasonal: "Outdoor cedar shower summer only" },
    amenities: ["free hot showers", "flush toilets", "free WiFi", "electrical hookups", "fire pit"],
    highlights: "Highest-rated campground in WA. Five shaded acres near Olympic NP and world-famous Second Beach.",
    driveFromSeattle: "4.5 hr",
    season: "Year-round",
    alerts: [],
    tips: "Book early — only 15 sites. The outdoor cedar shower in summer is an experience.",
    availability: generateAvailability(0.3),
    socialReviews: [
      { source: "Reddit r/OlympicNationalPark", user: "u/rainforest_runner", text: "The cedar shower alone is worth the trip. Hot water, surrounded by old growth — felt like a spa. Second Beach is a 5 min drive.", date: "2025-08" },
      { source: "Instagram", user: "@vanlife.pnw", text: "Our favorite spot on the entire Olympic Peninsula. The hosts are incredibly kind and the sites are well-spaced. You feel totally immersed in the rainforest.", date: "2025-07" },
      { source: "Reddit r/CampingandHiking", user: "u/beachcamp_addict", text: "Only downside is the drive from Seattle. But once you're there, it's pure magic. We stayed 4 nights and didn't want to leave.", date: "2025-06" },
    ]
  },
  {
    id: "pearrygin-lake",
    name: "Pearrygin Lake State Park",
    region: "North Cascades",
    location: "Winthrop, WA",
    lat: 48.4952,
    lng: -120.1414,
    platform: "WA State Parks",
    bookingUrl: "https://washington.goingtocamp.com",
    image: "https://photos.thedyrt.com/photo/643028/media/washington-pearrygin-lake-state-park_5dda8505-db7b-4e9b-8ab7-510c20b94344.jpg",
    pricePerNight: 38,
    reservationFee: 8,
    rating: 4.5,
    reviews: 29,
    sites: 147,
    siteTypes: ["tent", "RV"],
    showers: { type: "free", cost: "Free hot water", hours: "all day", seasonal: "March–October" },
    amenities: ["free hot showers", "flush toilets", "fire pit", "picnic table", "lake access", "swimming"],
    highlights: "Mountain-ringed lake near Winthrop. Stunning scenery, great base for North Cascades exploration.",
    driveFromSeattle: "4 hr",
    season: "March–October",
    alerts: [],
    tips: "Shower in the morning — water temp gets inconsistent in afternoons. Lakefront sites book first.",
    availability: generateAvailability(0.5),
    socialReviews: [
      { source: "Reddit r/WACamping", user: "u/methow_valley_fan", text: "Lakefront sites are everything. We swam every morning right from our campsite. Winthrop is a cute town 15 min away for coffee and supplies.", date: "2025-07" },
      { source: "The Dyrt", user: "FamilyCampers2025", text: "Great for kids — the beach area is shallow and safe. Showers are free but yeah, go in the morning for hot water. Afternoons are lukewarm at best.", date: "2025-08" },
    ]
  },
  {
    id: "moran",
    name: "Moran State Park",
    region: "San Juan Islands & Puget Sound",
    location: "Orcas Island, WA",
    lat: 48.6541,
    lng: -122.8312,
    platform: "WA State Parks",
    bookingUrl: "https://washington.goingtocamp.com",
    image: "https://photos.thedyrt.com/photo/34424/photo/washington-moran-state-park-midway_36ef0b6f6e2c91b7c5d7304efa546179.jpg",
    pricePerNight: 35,
    reservationFee: 8,
    rating: 4.7,
    reviews: 85,
    sites: 151,
    siteTypes: ["tent", "RV"],
    showers: { type: "token", cost: "Token-operated", hours: "all day", seasonal: "Summer" },
    amenities: ["showers (10 total, 4 ADA)", "flush toilets", "fire pit", "lake access", "kayak rental", "paddleboard"],
    highlights: "Climb Mt. Constitution for 360° island views. Kayak and paddleboard on mountain lakes. Island magic.",
    driveFromSeattle: "3 hr + ferry",
    season: "Year-round (limited winter)",
    alerts: [],
    tips: "Ferry reservations are essential in summer — book the Anacortes→Orcas ferry early.",
    availability: generateAvailability(0.4),
    socialReviews: [
      { source: "Reddit r/SanJuanIslands", user: "u/island_camper", text: "Mt. Constitution at sunrise is the best view in WA. Period. The drive up is wild but the tower view at the top is 360�� of islands, water, and mountains.", date: "2025-08" },
      { source: "Reddit r/WACamping", user: "u/kayak_king_pnw", text: "Rented kayaks on Cascade Lake right from camp. Water was perfect. Only struggle was getting the ferry reservation — book MONTHS ahead.", date: "2025-07" },
    ]
  },
  {
    id: "sun-lakes",
    name: "Sun Lakes-Dry Falls State Park",
    region: "Eastern Washington",
    location: "Coulee City, WA",
    lat: 47.6083,
    lng: -119.3628,
    platform: "WA State Parks",
    bookingUrl: "https://washington.goingtocamp.com",
    image: "https://photos.thedyrt.com/photo/667535/media/sun-lakes-park-resort_b8247fe3-9541-4799-9aab-73b5ea6b45c9.jpg",
    pricePerNight: 30,
    reservationFee: 8,
    rating: 4.4,
    reviews: 38,
    sites: 152,
    siteTypes: ["tent", "RV"],
    showers: { type: "free", cost: "Free hot water", hours: "all day", seasonal: "Spring–Fall" },
    amenities: ["free hot showers (12)", "flush toilets", "fire pit", "boat rental", "swimming beach", "fishing"],
    highlights: "Guaranteed sun. Geological wonder — Dry Falls was once the world's largest waterfall. Great for water sports.",
    driveFromSeattle: "3 hr",
    season: "April–October",
    alerts: [],
    tips: "Eastern WA summer = hot and dry. Bring extra water and sun protection. Way less crowded than west side.",
    availability: generateAvailability(0.7),
    socialReviews: [
      { source: "Reddit r/Washington", user: "u/eastern_wa_explorer", text: "The most underrated camping in WA. While everyone fights for spots on the coast, we had our pick of lakefront sites in July. 95°F and the lake was perfect.", date: "2025-07" },
      { source: "The Dyrt", user: "GeologyNerd42", text: "Dry Falls viewpoint blew my mind. 3.5 miles wide, 400ft tall — once 10x bigger than Niagara. Free hot showers too. My new favorite state park.", date: "2025-06" },
    ]
  },
  {
    id: "lake-easton",
    name: "Lake Easton State Park",
    region: "Central Cascades / I-90",
    location: "Easton, WA",
    lat: 47.2414,
    lng: -121.1867,
    platform: "WA State Parks",
    bookingUrl: "https://washington.goingtocamp.com",
    image: "https://photos.thedyrt.com/photo/686443/media/washington-lake-easton-state-park_a8ebac40-aeb7-415b-84c3-cf497d4b0f0b.jpg",
    pricePerNight: 30,
    reservationFee: 8,
    rating: 4.3,
    reviews: 42,
    sites: 148,
    siteTypes: ["tent", "RV"],
    showers: { type: "available", cost: "Included", hours: "all day", seasonal: "May–September" },
    amenities: ["showers (4 restrooms)", "flush toilets", "fire pit", "lake access", "swimming", "hiking"],
    highlights: "Easiest Cascades camping from Seattle — right off I-90. Lake Easton at 2,192 ft elevation.",
    driveFromSeattle: "1.2 hr",
    season: "May–September",
    alerts: ["Standard campground partially closed for cleanup in 2026 — utility sites 1-45 open"],
    tips: "Reservations open May 15, 2026 — book immediately for summer dates.",
    availability: generateAvailability(0.55),
    socialReviews: [
      { source: "Reddit r/SeattleWA", user: "u/weekend_warrior_206", text: "Our go-to for quick weekend trips. Just over an hour from Seattle, set up camp, swim in the lake. Nothing fancy but it works perfectly.", date: "2025-08" },
      { source: "Reddit r/WACamping", user: "u/i90_camper", text: "Utility sites 1-45 are open FCFS even when the main campground is closed. Got there Friday at noon and still had plenty of choices.", date: "2026-04" },
    ]
  },
  {
    id: "crescent-beach",
    name: "Crescent Beach & RV Park",
    region: "Olympic Peninsula",
    location: "Port Angeles, WA",
    lat: 48.0962,
    lng: -123.7502,
    platform: "Hipcamp",
    bookingUrl: "https://www.hipcamp.com/en-US/washington/port-angeles",
    image: "https://hipcamp-res.cloudinary.com/f_jpg,c_fill,w_800,h_600,q_80/v1681428322/land-photos/vi4aeilibbmqop9yrszq.jpg",
    pricePerNight: 42,
    reservationFee: 0,
    rating: 4.7,
    reviews: 326,
    sites: 67,
    siteTypes: ["tent", "RV", "lodging"],
    showers: { type: "coin-op", cost: "Quarter-operated", hours: "7am��9pm", seasonal: "Summer" },
    amenities: ["hot showers", "full hookups", "laundry", "beach access", "fire pit", "picnic table"],
    highlights: "Half-mile sandy beach with Olympic NP proximity. Water activities and stunning mountain views.",
    driveFromSeattle: "3 hr",
    season: "Year-round",
    alerts: [],
    tips: "Bring quarters for the showers. Beach sites are the premium spots — book early.",
    availability: generateAvailability(0.5),
    socialReviews: [
      { source: "Reddit r/OlympicNationalPark", user: "u/port_angeles_local", text: "Best beach camping near Olympic NP. The views of the Strait with the mountains behind are incredible at sunset. Bring quarters for showers though.", date: "2025-07" },
      { source: "The Dyrt", user: "RVlife_PNW", text: "Full hookups, laundry, and beach access? For RV camping near Olympic, this can't be beat. Sites are tight but the location makes up for it.", date: "2025-08" },
    ]
  },
  {
    id: "lake-wenatchee",
    name: "Lake Wenatchee State Park",
    region: "Central Cascades / I-90",
    location: "Leavenworth, WA",
    lat: 47.8128,
    lng: -120.7286,
    platform: "WA State Parks",
    bookingUrl: "https://washington.goingtocamp.com",
    image: "https://photos.thedyrt.com/photo/34114/photo/washington-lake-wenatchee-state-park_1aa939b77bf34b634e9481096a6c3702.jpg",
    pricePerNight: 35,
    reservationFee: 8,
    rating: 4.5,
    reviews: 64,
    sites: 197,
    siteTypes: ["tent", "RV"],
    showers: { type: "free", cost: "Free hot water", hours: "all day", seasonal: "Summer" },
    amenities: ["hot showers", "flush toilets", "fire pit", "lake access", "swimming", "horseback riding"],
    highlights: "Glacier-fed lake near Leavenworth. Two campground areas — South (lake) and North (river). Mountain backdrop.",
    driveFromSeattle: "2.5 hr",
    season: "May–October",
    alerts: [],
    tips: "South campground has lake access; North is quieter with river access. Leavenworth is 20 min away for food/shopping.",
    availability: generateAvailability(0.45),
    socialReviews: [
      { source: "Reddit r/Leavenworth", user: "u/cascade_explorer", text: "South campground lake access is amazing — glacier-fed water so it's cold but on a hot day it's perfect. Leavenworth 20 min away for the best bratwurst of your life.", date: "2025-07" },
      { source: "Instagram", user: "@pnw.camplife", text: "The mountain backdrop from the lake is straight out of a postcard. We did horseback riding through the park trails and it was the highlight of our summer.", date: "2025-08" },
    ]
  },
  {
    id: "twin-harbors",
    name: "Twin Harbors Beach State Park",
    region: "Southwest WA Coast",
    location: "Westport, WA",
    lat: 46.8329,
    lng: -124.1064,
    platform: "WA State Parks",
    bookingUrl: "https://washington.goingtocamp.com",
    image: "https://photos.thedyrt.com/photo/45448/photo/washington-twin-harbors-state-park_e8db287a9af32971ba922687a9744139.jpg",
    pricePerNight: 30,
    reservationFee: 8,
    rating: 4.2,
    reviews: 31,
    sites: 250,
    siteTypes: ["tent", "RV"],
    showers: { type: "available", cost: "Included", hours: "all day", seasonal: "Year-round" },
    amenities: ["showers", "flush toilets", "fire pit", "beach access", "kite flying", "clamming"],
    highlights: "172 acres on the Pacific coast. Windswept beach camping, storm watching, razor clamming in season.",
    driveFromSeattle: "2.5 hr",
    season: "Year-round",
    alerts: [],
    tips: "Bring layers — the coast is cooler and windier than inland. Great for kite flying.",
    availability: generateAvailability(0.65),
    socialReviews: [
      { source: "Reddit r/WACamping", user: "u/beach_camper_wa", text: "This park is our go-to for coast camping. Not glamorous but 250 sites means you can almost always get in. The beach is massive and mostly empty.", date: "2025-06" },
      { source: "The Dyrt", user: "KiteFlyer_WA", text: "The wind here is insane in the best way. Perfect for kite flying. Razor clamming in season is super fun if you have a license.", date: "2025-10" },
    ]
  },
  {
    id: "waterfall-sanctuary",
    name: "Waterfall Sanctuary",
    region: "Southwest Cascades",
    location: "Carson, WA",
    lat: 45.7285,
    lng: -121.8102,
    platform: "Hipcamp",
    bookingUrl: "https://www.hipcamp.com/en-US/washington/carson",
    image: "https://hipcamp-res.cloudinary.com/f_jpg,c_fill,w_800,h_600,q_80/v1624486144/campground-photos/fple2boclgbjnrc3hppy.jpg",
    pricePerNight: 55,
    reservationFee: 0,
    rating: 4.7,
    reviews: 597,
    sites: 10,
    siteTypes: ["tent", "RV", "lodging"],
    showers: { type: "available", cost: "Included", hours: "all day", seasonal: "Year-round" },
    amenities: ["wood-fired sauna", "café", "stargazer tents", "fire pit", "creek access"],
    highlights: "17 acres bordered by Gifford Pinchot National Forest. Wood-fired sauna, on-site café, waterfall access.",
    driveFromSeattle: "3.5 hr",
    season: "Year-round",
    alerts: [],
    tips: "The wood-fired sauna is the real draw here. Stargazer tents are a unique glamping experience.",
    availability: generateAvailability(0.35),
    socialReviews: [
      { source: "Reddit r/glamping", user: "u/stargazer_nw", text: "The stargazer tents are next level. Fall asleep watching stars through the clear roof. The wood-fired sauna after a hike in the gorge is perfection.", date: "2025-09" },
      { source: "Instagram", user: "@pnw.hidden.gems", text: "This place is a vibe. Café serves amazing local coffee, the creek is crystal clear, and the sauna is one of the best we've experienced anywhere. Not cheap but worth every penny.", date: "2025-08" },
    ]
  },
  {
    id: "ohanapecosh",
    name: "Ohanapecosh Campground",
    region: "Mount Rainier",
    location: "Mount Rainier NP, WA",
    lat: 46.7340,
    lng: -121.5684,
    platform: "Recreation.gov",
    bookingUrl: "https://www.recreation.gov/camping/campgrounds/232465",
    image: "https://photos.thedyrt.com/photo/28440/photo/washington-ohanapecosh-campground_4bbfa19fe2e91eb32a2f4e2d18f8301e.jpg",
    pricePerNight: 30,
    reservationFee: 6,
    rating: 4.6,
    reviews: 142,
    sites: 188,
    siteTypes: ["tent", "RV"],
    showers: { type: "none", cost: "No showers", hours: "N/A", seasonal: "N/A" },
    amenities: ["flush toilets", "potable water", "fire pit", "picnic table", "amphitheater", "old growth forest"],
    highlights: "Most popular campground in Mt. Rainier NP. Old growth forest, snow-fed river, convenient to Paradise and Sunrise.",
    driveFromSeattle: "2.5 hr",
    season: "Late May–Late September",
    alerts: ["No showers at any Mt. Rainier NP campground"],
    tips: "Reserve exactly 6 months ahead on the 15th at 10am ET. The Grove of the Patriarchs trail starts from here.",
    availability: generateAvailability(0.25),
    socialReviews: [
      { source: "Reddit r/MountRainier", user: "u/rainier_regular", text: "Best campground in the park hands down. The old growth trees are massive. River is gorgeous but freezing. No showers — hit up Packwood on the way out.", date: "2025-08" },
      { source: "The Dyrt", user: "NWHiker2024", text: "Got our spot by setting an alarm for 7am PT on release day. Sites along the river (B loop) are the best. Bring layers, it's cool even in August.", date: "2025-07" },
    ]
  },
  {
    id: "kalaloch",
    name: "Kalaloch Campground",
    region: "Olympic Peninsula",
    location: "Olympic NP, WA",
    lat: 47.6131,
    lng: -124.3739,
    platform: "Recreation.gov",
    bookingUrl: "https://www.recreation.gov/camping/campgrounds/232464",
    image: "https://photos.thedyrt.com/photo/17183/photo/washington-kalaloch-campground_b1e49698f4e44a3becc74ce9f2be4a3e.jpg",
    pricePerNight: 28,
    reservationFee: 6,
    rating: 4.5,
    reviews: 110,
    sites: 170,
    siteTypes: ["tent", "RV"],
    showers: { type: "none", cost: "No showers", hours: "N/A", seasonal: "N/A" },
    amenities: ["flush toilets", "potable water", "fire pit", "beach access", "bluff-top sites", "ocean views"],
    highlights: "Bluff-top oceanfront camping in Olympic NP. Some of the most dramatic coastal campsites in the Pacific Northwest.",
    driveFromSeattle: "4 hr",
    season: "Year-round (some loops seasonal)",
    alerts: ["No showers — nearest at Kalaloch Lodge or Bogachiel SP (23 mi)"],
    tips: "Sites on the bluff edge have direct ocean views — worth requesting specifically. Tree of Life beach is a short walk.",
    availability: generateAvailability(0.3),
    socialReviews: [
      { source: "Reddit r/OlympicNationalPark", user: "u/coastal_camper_pnw", text: "Falling asleep to the sound of the ocean crashing below the bluff is something else. No showers but honestly who cares when you have this view.", date: "2025-07" },
      { source: "Instagram", user: "@pnw.adventure.co", text: "Kalaloch is bucket list camping. Sunset from the bluff sites is the most beautiful thing I've seen in WA. Go see the Tree of Life while you're there.", date: "2025-08" },
    ]
  },
  {
    id: "colonial-creek",
    name: "Colonial Creek South",
    region: "North Cascades",
    location: "North Cascades NP, WA",
    lat: 48.6875,
    lng: -121.0958,
    platform: "Recreation.gov",
    bookingUrl: "https://www.recreation.gov/camping/campgrounds/255201",
    image: "https://photos.thedyrt.com/photo/81437/media/washington-colonial-creek-south-campground_b59dcdef39cd2ed17aa16e1f9b2e0a0a.jpg",
    pricePerNight: 22,
    reservationFee: 6,
    rating: 4.7,
    reviews: 68,
    sites: 93,
    siteTypes: ["tent", "RV"],
    showers: { type: "none", cost: "No showers", hours: "N/A", seasonal: "N/A" },
    amenities: ["flush toilets", "potable water", "fire pit", "lake access", "boat launch", "hiking"],
    highlights: "Waterfront camping on turquoise Diablo Lake in North Cascades NP. Jaw-dropping mountain views and glacier-fed water.",
    driveFromSeattle: "3 hr",
    season: "Mid-May–Mid-October",
    alerts: ["No showers — vault and flush toilets only"],
    tips: "Diablo Lake's turquoise color comes from glacial flour. The Diablo Lake overlook on Hwy 20 is an iconic photo spot.",
    availability: generateAvailability(0.35),
    socialReviews: [
      { source: "Reddit r/WACamping", user: "u/north_cascades_addict", text: "The color of Diablo Lake is not photoshopped — it really is that turquoise. Best campground in North Cascades for lakeside access. No showers but the lake is your shower.", date: "2025-08" },
      { source: "The Dyrt", user: "PNWExplorer", text: "Incredibly underrated. $22/night for lakefront camping with those views? The lack of showers is the only reason it's not completely sold out.", date: "2025-07" },
    ]
  },
  {
    id: "sol-duc-hot-springs",
    name: "Sol Duc Hot Springs Resort Campground",
    region: "Olympic Peninsula",
    location: "Olympic NP, WA",
    lat: 47.9686,
    lng: -123.8601,
    platform: "Recreation.gov",
    bookingUrl: "https://www.recreation.gov/camping/campgrounds/251906",
    image: "https://photos.thedyrt.com/photo/48498/photo/washington-sol-duc-hot-springs-resort-campground_a31a66023ae7cb08b8fe6e6334a6d3c8.jpg",
    pricePerNight: 24,
    reservationFee: 6,
    rating: 4.4,
    reviews: 73,
    sites: 82,
    siteTypes: ["tent", "RV"],
    showers: { type: "hot-springs", cost: "Hot springs pool access (fee)", hours: "varies", seasonal: "Seasonal resort" },
    amenities: ["hot springs pools (paid)", "flush toilets", "potable water", "fire pit", "restaurant nearby", "hiking"],
    highlights: "Camp next to natural hot springs in Olympic NP. The Sol Duc Falls trail starts from the campground — one of the park's best hikes.",
    driveFromSeattle: "4.5 hr",
    season: "Late March–Late October",
    alerts: ["Hot springs pool requires separate day-use fee (~$15)"],
    tips: "The hot springs are the ultimate shower alternative. Sol Duc Falls is a must-do 1.6mi roundtrip hike from camp.",
    availability: generateAvailability(0.3),
    socialReviews: [
      { source: "Reddit r/OlympicNationalPark", user: "u/hot_springs_hiker", text: "After a long day hiking, soaking in the hot springs is absolute heaven. The campground itself is nothing fancy but the location can't be beat.", date: "2025-07" },
      { source: "Reddit r/WACamping", user: "u/sol_duc_lover", text: "Pro tip: hike to Sol Duc Falls first thing in the morning when no one's there. The light through the forest is magical. Then hit the hot springs after.", date: "2025-08" },
    ]
  }
];

function generateAvailability(fillRate) {
  const avail = {};
  const start = new Date("2026-06-01");
  const end = new Date("2026-09-30");
  for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
    const key = d.toISOString().split("T")[0];
    const dayOfWeek = d.getDay();
    const isWeekend = dayOfWeek === 5 || dayOfWeek === 6 || dayOfWeek === 0;
    const baseChance = isWeekend ? fillRate * 0.4 : fillRate;
    const isHoliday = (d.getMonth() === 6 && d.getDate() >= 3 && d.getDate() <= 5) ||
                      (d.getMonth() === 8 && d.getDate() >= 4 && d.getDate() <= 6);
    const chance = isHoliday ? fillRate * 0.15 : baseChance;
    const available = Math.floor(Math.random() * 20 * chance);
    avail[key] = { available, total: 20 };
  }
  return avail;
}
