export const campsites = [
  {
    id: "deception-pass",
    name: "Deception Pass State Park",
    region: "San Juan Islands & Puget Sound",
    location: "Anacortes, WA",
    platform: "GoingToCamp",
    bookingUrl: "https://washington.goingtocamp.com",
    image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80",
    pricePerNight: 35,
    reservationFee: 8,
    rating: 4.5,
    reviews: 109,
    sites: 326,
    siteTypes: ["tent", "RV", "cabin"],
    showers: { type: "coin-op", cost: "$1 = 4 tokens (3 min each)", hours: "all day", seasonal: "Spring–Thanksgiving" },
    amenities: ["hot showers", "flush toilets", "fire pit", "picnic table", "potable water", "boat launch"],
    highlights: "WA's most popular state park. Dramatic bridge 180ft above tidal currents, old growth trails, beach access.",
    driveFromSeattle: "1.5 hr",
    season: "Year-round (water spring–Thanksgiving)",
    alerts: ["Bowman Bay pier closed indefinitely", "No vehicles over 25ft at West Beach"],
    tips: "Cranberry Loop has the best shade. Sites C-30 to C-50 are closest to showers."
  },
  {
    id: "shangri-la-push",
    name: "Shangri La Push",
    region: "Olympic Peninsula",
    location: "Forks, WA",
    platform: "Hipcamp",
    bookingUrl: "https://www.hipcamp.com/en-US/washington/forks",
    image: "https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=600&q=80",
    pricePerNight: 45,
    reservationFee: 0,
    rating: 4.9,
    reviews: 2124,
    sites: 15,
    siteTypes: ["tent", "RV"],
    showers: { type: "free", cost: "Free hot water", hours: "all day", seasonal: "Outdoor cedar shower summer only" },
    amenities: ["free hot showers", "flush toilets", "free WiFi", "electrical hookups", "fire pit"],
    highlights: "Highest-rated campground in WA. Five shaded acres near Olympic NP and world-famous Second Beach.",
    driveFromSeattle: "4.5 hr",
    season: "Year-round",
    alerts: [],
    tips: "Book early — only 15 sites. The outdoor cedar shower in summer is an experience."
  },
  {
    id: "pearrygin-lake",
    name: "Pearrygin Lake State Park",
    region: "North Cascades",
    location: "Winthrop, WA",
    platform: "GoingToCamp",
    bookingUrl: "https://washington.goingtocamp.com",
    image: "https://images.unsplash.com/photo-1533873984035-25970ab07461?w=600&q=80",
    pricePerNight: 38,
    reservationFee: 8,
    rating: 4.5,
    reviews: 29,
    sites: 147,
    siteTypes: ["tent", "RV"],
    showers: { type: "free", cost: "Free hot water", hours: "all day", seasonal: "March–October" },
    amenities: ["free hot showers", "flush toilets", "fire pit", "picnic table", "lake access", "swimming"],
    highlights: "Mountain-ringed lake near Winthrop. Stunning scenery, great base for North Cascades exploration.",
    driveFromSeattle: "4 hr",
    season: "March–October",
    alerts: [],
    tips: "Shower in the morning — water temp gets inconsistent in afternoons. Lakefront sites book first."
  },
  {
    id: "moran",
    name: "Moran State Park",
    region: "San Juan Islands & Puget Sound",
    location: "Orcas Island, WA",
    platform: "GoingToCamp",
    bookingUrl: "https://washington.goingtocamp.com",
    image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80",
    pricePerNight: 35,
    reservationFee: 8,
    rating: 4.7,
    reviews: 85,
    sites: 151,
    siteTypes: ["tent", "RV"],
    showers: { type: "token", cost: "Token-operated", hours: "all day", seasonal: "Summer" },
    amenities: ["showers (10 total, 4 ADA)", "flush toilets", "fire pit", "lake access", "kayak rental", "paddleboard"],
    highlights: "Climb Mt. Constitution for 360° island views. Kayak and paddleboard on mountain lakes. Island magic.",
    driveFromSeattle: "3 hr + ferry",
    season: "Year-round (limited winter)",
    alerts: [],
    tips: "Ferry reservations are essential in summer — book the Anacortes→Orcas ferry early."
  },
  {
    id: "sun-lakes",
    name: "Sun Lakes-Dry Falls State Park",
    region: "Eastern Washington",
    location: "Coulee City, WA",
    platform: "GoingToCamp",
    bookingUrl: "https://washington.goingtocamp.com",
    image: "https://images.unsplash.com/photo-1517824806704-9040b037703b?w=600&q=80",
    pricePerNight: 30,
    reservationFee: 8,
    rating: 4.4,
    reviews: 38,
    sites: 152,
    siteTypes: ["tent", "RV"],
    showers: { type: "free", cost: "Free hot water", hours: "all day", seasonal: "Spring–Fall" },
    amenities: ["free hot showers (12)", "flush toilets", "fire pit", "boat rental", "swimming beach", "fishing"],
    highlights: "Guaranteed sun. Geological wonder — Dry Falls was once the world's largest waterfall. Great for water sports.",
    driveFromSeattle: "3 hr",
    season: "April–October",
    alerts: [],
    tips: "Eastern WA summer = hot and dry. Bring extra water and sun protection. Way less crowded than west side."
  },
  {
    id: "lake-easton",
    name: "Lake Easton State Park",
    region: "Central Cascades / I-90",
    location: "Easton, WA",
    platform: "GoingToCamp",
    bookingUrl: "https://washington.goingtocamp.com",
    image: "https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?w=600&q=80",
    pricePerNight: 30,
    reservationFee: 8,
    rating: 4.3,
    reviews: 42,
    sites: 148,
    siteTypes: ["tent", "RV"],
    showers: { type: "available", cost: "Included", hours: "all day", seasonal: "May–September" },
    amenities: ["showers (4 restrooms)", "flush toilets", "fire pit", "lake access", "swimming", "hiking"],
    highlights: "Easiest Cascades camping from Seattle — right off I-90. Lake Easton at 2,192 ft elevation.",
    driveFromSeattle: "1.2 hr",
    season: "May–September",
    alerts: ["Standard campground partially closed for cleanup in 2026 — utility sites 1-45 open"],
    tips: "Reservations open May 15, 2026 — book immediately for summer dates."
  },
  {
    id: "crescent-beach",
    name: "Crescent Beach & RV Park",
    region: "Olympic Peninsula",
    location: "Port Angeles, WA",
    platform: "Hipcamp",
    bookingUrl: "https://www.hipcamp.com/en-US/washington/port-angeles",
    image: "https://images.unsplash.com/photo-1500581276021-a4bbcd0601af?w=600&q=80",
    pricePerNight: 42,
    reservationFee: 0,
    rating: 4.7,
    reviews: 326,
    sites: 67,
    siteTypes: ["tent", "RV", "lodging"],
    showers: { type: "coin-op", cost: "Quarter-operated", hours: "7am–9pm", seasonal: "Summer" },
    amenities: ["hot showers", "full hookups", "laundry", "beach access", "fire pit", "picnic table"],
    highlights: "Half-mile sandy beach with Olympic NP proximity. Water activities and stunning mountain views.",
    driveFromSeattle: "3 hr",
    season: "Year-round",
    alerts: [],
    tips: "Bring quarters for the showers. Beach sites are the premium spots — book early."
  },
  {
    id: "lake-wenatchee",
    name: "Lake Wenatchee State Park",
    region: "Central Cascades / I-90",
    location: "Leavenworth, WA",
    platform: "GoingToCamp",
    bookingUrl: "https://washington.goingtocamp.com",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80",
    pricePerNight: 35,
    reservationFee: 8,
    rating: 4.5,
    reviews: 64,
    sites: 197,
    siteTypes: ["tent", "RV"],
    showers: { type: "free", cost: "Free hot water", hours: "all day", seasonal: "Summer" },
    amenities: ["hot showers", "flush toilets", "fire pit", "lake access", "swimming", "horseback riding"],
    highlights: "Glacier-fed lake near Leavenworth. Two campground areas — South (lake) and North (river). Mountain backdrop.",
    driveFromSeattle: "2.5 hr",
    season: "May–October",
    alerts: [],
    tips: "South campground has lake access; North is quieter with river access. Leavenworth is 20 min away for food/shopping."
  },
  {
    id: "twin-harbors",
    name: "Twin Harbors Beach State Park",
    region: "Southwest WA Coast",
    location: "Westport, WA",
    platform: "GoingToCamp",
    bookingUrl: "https://washington.goingtocamp.com",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
    pricePerNight: 30,
    reservationFee: 8,
    rating: 4.2,
    reviews: 31,
    sites: 250,
    siteTypes: ["tent", "RV"],
    showers: { type: "available", cost: "Included", hours: "all day", seasonal: "Year-round" },
    amenities: ["showers", "flush toilets", "fire pit", "beach access", "kite flying", "clamming"],
    highlights: "172 acres on the Pacific coast. Windswept beach camping, storm watching, razor clamming in season.",
    driveFromSeattle: "2.5 hr",
    season: "Year-round",
    alerts: [],
    tips: "Bring layers — the coast is cooler and windier than inland. Great for kite flying."
  },
  {
    id: "deception-pass-hipcamp",
    name: "Waterfall Sanctuary",
    region: "Southwest Cascades",
    location: "Carson, WA",
    platform: "Hipcamp",
    bookingUrl: "https://www.hipcamp.com/en-US/washington/carson",
    image: "https://images.unsplash.com/photo-1471115853179-bb1d604434e0?w=600&q=80",
    pricePerNight: 55,
    reservationFee: 0,
    rating: 4.7,
    reviews: 597,
    sites: 10,
    siteTypes: ["tent", "RV", "lodging"],
    showers: { type: "available", cost: "Included", hours: "all day", seasonal: "Year-round" },
    amenities: ["wood-fired sauna", "café", "stargazer tents", "fire pit", "creek access"],
    highlights: "17 acres bordered by Gifford Pinchot National Forest. Wood-fired sauna, on-site café, waterfall access.",
    driveFromSeattle: "3.5 hr",
    season: "Year-round",
    alerts: [],
    tips: "The wood-fired sauna is the real draw here. Stargazer tents are a unique glamping experience."
  }
];
